baseURL = 'https://globalemgt.github.io/clc-website/'
languageCode = 'en'
title = 'Controlled Lighting Corp.'

[menu]
[[menu.main_menu]]
  identifier = "company"
  name = "Company"
  url = "/about-us"
  weight = 1

[[menu.main_menu]]
  parent = "company"
  name = "About Us"
  url = "/about-us"
  weight = 1

[[menu.main_menu]]
  parent = "company"
  identifier = "baa-taa-compliance"
  name = "BAA & TAA Compliance"
  url = "/baa-taa-compliance"
  weight = 2

[[menu.main_menu]]
  parent = "company"
  identifier = "our-partners"
  name = "Our Partners"
  url = "/our-partners"
  weight = 3

[[menu.main_menu]]
  parent = "company"
  identifier = "leadership"
  name = "Leadership"
  url = "/leadership"
  weight = 4

[[menu.main_menu]]
  identifier = "supply-partners"
  name = "Supply Partners"
  url = "/our-partners"
  weight = 2

[[menu.main_menu]]
  parent = "supply-partners"
  identifier = "maxlite"
  name = "Maxlite"
  url = "/maxlite"
  weight = 1

[[menu.main_menu]]
  parent = "supply-partners"
  identifier = "maxlite-c-max"
  name = "MaxLite C-Max RF Lighting Controls"
  url = "/maxlite/c-max-rf-lighting-controls"
  weight = 2

[[menu.main_menu]]
  parent = "supply-partners"
  identifier = "maxlite-mseries"
  name = "MaxLite M Series"
  url = "/maxlite/mseries"
  weight = 3

[[menu.main_menu]]
  parent = "supply-partners"
  identifier = "maxlite-rcf-series"
  name = "MaxLite RCF Series"
  url = "/maxlite/rcf-series"
  weight = 4

[[menu.main_menu]]
  parent = "supply-partners"
  identifier = "maxlite-evmax"
  name = "EVMax+"
  url = "/maxlite/evmax"
  weight = 5

[[menu.main_menu]]
  identifier = "resources"
  name = "Resources"
  url = "/resources"
  weight = 3

[[menu.main_menu]]
  identifier = "contact-us"
  name = "Contact"
  url = "/contact-us"
  weight = 4



[Params]
siteLogo = "assets/wp-content/uploads/2019/12/BlueCirclelightCLC-2018-300x115.png"
